// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_8VCCGo-5QCP8-TZ2s9S2_AAW0u11mmY',
    appId: '1:648529180074:web:260fc3b966a2f5a37a27d3',
    messagingSenderId: '648529180074',
    projectId: 'urbanflora-dev',
    authDomain: 'urbanflora-dev.firebaseapp.com',
    storageBucket: 'urbanflora-dev.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9HAxMargdJ9b-goaZo5T0Jb9aagB_U2s',
    appId: '1:648529180074:android:92883dff340336387a27d3',
    messagingSenderId: '648529180074',
    projectId: 'urbanflora-dev',
    storageBucket: 'urbanflora-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3SQxeqnB3FmKRKbsfTNWWgR7AQow_Hhw',
    appId: '1:648529180074:ios:017f2b7f701595987a27d3',
    messagingSenderId: '648529180074',
    projectId: 'urbanflora-dev',
    storageBucket: 'urbanflora-dev.firebasestorage.app',
    iosBundleId: 'com.urbanflora.urbanFlora',
  );
}
